### ISSUE TITLE
Input of DCN

### ISSUE THREAD

**Issue by kjy09** [iGuoYanjun/C2ANet#1]
Dear authors,

Thanks for your great work. I have a problem when running the source code. Specifically, the DCN of mmcv does not take a list as input. What should I do to make it work?

**Comment by iGuoYanjun** [comment]
As I mentioned in Readme.md, please replace the original deform_conv.py with the file we provided.

**Comment by kjy09** [comment]
OK. Thanks again for your kindly reply.
